.PHONY: clean All

All:
	@echo "----------Building project:[ 7-3_ADT_vector -  ]----------"
	@cd "7-3_ADT_vector" && "$(MAKE)" -f  "7-3_ADT_vector.mk"
clean:
	@echo "----------Cleaning project:[ 7-3_ADT_vector -  ]----------"
	@cd "7-3_ADT_vector" && "$(MAKE)" -f  "7-3_ADT_vector.mk" clean
