.PHONY: clean All

All:
	@echo "----------Building project:[ 8-3_Victim -  ]----------"
	@cd "8-3_Victim" && "$(MAKE)" -f  "8-3_Victim.mk"
clean:
	@echo "----------Cleaning project:[ 8-3_Victim -  ]----------"
	@cd "8-3_Victim" && "$(MAKE)" -f  "8-3_Victim.mk" clean
